### PR TITLE
Use ?assertEqual macro instead of ?assert

### LINKED ISSUE #242: Raindrops tests are not very informative
Hello :)

Thank you for your work on Erlang track!

I just started it and got to the **Raindrops** exercise. This is the first exercise with such tests:

```erlang
sound_of_52_is_52_test() ->
    ?assert( raindrops:convert(52) =:= "52").
```

https://github.com/exercism/erlang/blob/master/exercises/raindrops/test/raindrops_tests.erl

The problem with such tests for me is that they don't suggest what is wrong with my code.

```
        raindrops_tests: sound_of_52_is_52_test...*failed*
in function raindrops_tests:'-sound_of_52_is_52_test/0-fun-0-'/0 (/Users/vassilevsky/Dropbox/exercism/erlang/raindrops/_build/test/lib/raindrops/test/raindrops_tests.erl, line 43)
**error:{assert,[{module,raindrops_tests},
         {line,43},
         {expression,"raindrops : convert ( 52 ) =:= \"52\""},
         {expected,true},
         {value,false}]}
  output:<<"">>
```

I can understand that my function returned **not "52"**. But what did it return? That I don't know and therefore have trouble understanding what is wrong with it.

I think that it would be better to use `?assertEqual` like in all previous tests.

I will happily send a PR but I'm not sure what is the correct way to solve this. There's this comment in the tests:

```
% test cases adapted from `x-common//canonical-data.json` @ version: 1.0.0
```

It looks like there is a template somewhere, from which the tests are auto-generated, but I have failed to locate it :)

### PR DESCRIPTION
**Pull request by vassilevsky**
It will display incorrect values in test failure messages, which will be more helpful to the programmer.

Closes #242.

### CODE REVIEW

File: exercises/raindrops/test/raindrops_tests.erl [hunk 1]
```diff
@@ -3,48 +3,59 @@
...
-    ?assert( raindrops:convert(105) =:= "PlingPlangPlong").
+    ?assertEqual("PlingPlangPlong", raindrops:convert(105)).
+
 sound_of_3125_is_Plang_test() ->
-    ?assert( raindrops:convert(3125) =:= "Plang").
+    ?assertEqual("Plang", raindrops:convert(3125)).
 
 version_test() ->
-  ?assertMatch(1, raindrops:test_version()).
+  ?assertEqual(1, raindrops:test_version()).
```
Comment (NobbZ) [inline exercises/raindrops/test/raindrops_tests.erl]: Please leave this as `?assertMatch`, as `?assertEqual(1, 1.0)` will pass.

Comment (vassilevsky) [reply exercises/raindrops/test/raindrops_tests.erl]: It doesn't pass:

```
        raindrops_tests: version_test...*failed*
in function raindrops_tests:'-version_test/0-fun-0-'/0 (/Users/vassilevsky/Dropbox/exercism/erlang/raindrops/_build/test/lib/raindrops/test/raindrops_tests.erl, line 61)
**error:{assertEqual,[{module,raindrops_tests},
              {line,61},
              {expression,"1.0"},
              {expected,1},
              {value,1.0}]}
  output:<<"">>
```

I believe `?assertEqual` does strict equality check (`=:=`).

Comment (NobbZ) [reply exercises/raindrops/test/raindrops_tests.erl]: Okay, then I was missinformed about this.
